spring:
  application:
  name: Equipment
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;NON_KEYWORDS=VALUE;
    username: root
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
